### ISSUE TITLE
CityCmb_Init

### ISSUE THREAD

**Issue by Corobori** [DevExpress-Examples/aspxgridview-how-to-implement-cascading-combo-boxes-in-batch-edit-mode-by-using-webmethods-t356740#1]
In your sample code Default.aspx.vb, I see a sub called CityCmb_Init and I don't see it being called from anywhere.  Removing it the project compiles and seems to work. Or am I missing anything ?

**Comment by dxstanley** [comment]
Hello,

Thank you for contacting us. You are right, the "CityCmb_Init" method is not needed in this example. We will correct the example as soon as possible.
